version: "3.3"
services:
  b-hunters-dalfox:
    image: bormaa/b-hunters-dalfox:v1.0
    restart: always
    deploy:
      replicas: 1
    environment:
      - workers_num=100
    volumes:
      - ./config/b-hunters.ini:/etc/b-hunters/b-hunters.ini
  b-hunters-dirsearch:
    image: bormaa/b-hunters-dirsearch:v1.0
    restart: always
    deploy:
      replicas: 1
    environment:
      - deepscan=False
      - max_threads=200
    volumes:
      - ./config/b-hunters.ini:/etc/b-hunters/b-hunters.ini
  b-hunters-getjs:
    image: bormaa/b-hunters-getjs:v1.0
    restart: always
    deploy:
      replicas: 1
    volumes:
      - ./config/b-hunters.ini:/etc/b-hunters/b-hunters.ini
  b-hunters-gowitness:
    image: bormaa/b-hunters-gowitness:v1.0
    restart: always
    deploy:
      replicas: 1
    volumes:
      - ./config/b-hunters.ini:/etc/b-hunters/b-hunters.ini
  b-hunters-jsscanner:
    image: bormaa/b-hunters-jsscanner:v1.0
    restart: always
    deploy:
      replicas: 1
    volumes:
      - ./config/b-hunters.ini:/etc/b-hunters/b-hunters.ini
  b-hunters-katana:
    image: bormaa/b-hunters-katana:v1.0
    restart: always
    deploy:
      replicas: 1
    volumes:
      - ./config/b-hunters.ini:/etc/b-hunters/b-hunters.ini
  b-hunters-nmap:
    image: bormaa/b-hunters-nmap:v1.0
    restart: always
    deploy:
      replicas: 1
    volumes:
      - ./config/b-hunters.ini:/etc/b-hunters/b-hunters.ini
  b-hunters-nuclei:
    image: bormaa/b-hunters-nuclei:v1.0
    restart: always
    deploy:
      replicas: 1
    environment:
      - scan_type=Domain
      # - scan_type=Full # Use full if you want to scan doamins and paths but this is cpu and memory intensive
    volumes:
      - ./config/b-hunters.ini:/etc/b-hunters/b-hunters.ini
  b-hunters-paramspider:
    image: bormaa/b-hunters-paramspider:v1.0
    restart: always
    deploy:
      replicas: 1
    volumes:
      - ./config/b-hunters.ini:/etc/b-hunters/b-hunters.ini
  b-hunters-gospider:
    image: bormaa/b-hunters-gospider:v1.0
    restart: always
    deploy:
      replicas: 1
    volumes:
      - ./config/b-hunters.ini:/etc/b-hunters/b-hunters.ini
  b-hunters-sqlmap:
    image: bormaa/b-hunters-sqlmap:v1.0
    restart: always
    deploy:
      replicas: 1
    environment:
      - process_num=15
      - process_timeout=900
    volumes:
      - ./config/b-hunters.ini:/etc/b-hunters/b-hunters.ini
  b-hunters-ssti-checker:
    image: bormaa/b-hunters-ssti-checker:v1.0
    restart: always
    deploy:
      replicas: 1
    environment:
      - process_num=15
      - process_timeout=600
    volumes:
      - ./config/b-hunters.ini:/etc/b-hunters/b-hunters.ini
  b-hunters-subrecon:
    image: bormaa/b-hunters-subrecon:v1.0
    restart: always
    deploy:
      replicas: 1
    environment:
      - CHAOS_KEY=""
      - PDCP_API_KEY=""
      # - BINARYEDGE_TOKEN=""
      # - FB_APP_ID=""
      # - FB_APP_SECRET=""
      # - SPYSE_TOKEN=""
      # - SECURITY_TRAILS_KEY=""
      # - C99_KEY=""
      # - PASSIVETOTAL_KEY=""
      # - PASSIVETOTAL_SECRET=""
      # - INTELX_KEY=""
      # - INTELX_URL=""
      # - findomain_fb_token=""
      # - findomain_virustotal_token=""
      # - findomain_securitytrails_token=""
      # - VT_API_KEY=""
      # - SPYSE_API_TOKEN="
    volumes:
      - ./config/b-hunters.ini:/etc/b-hunters/b-hunters.ini
  b-hunters-wayback:
    image: bormaa/b-hunters-wayback:v1.0
    restart: always
    deploy:
      replicas: 1
    volumes:
      - ./config/b-hunters.ini:/etc/b-hunters/b-hunters.ini
  b-hunters-web-technology:
    image: bormaa/b-hunters-web-technology:v1.0
    restart: always
    deploy:
      replicas: 1
    volumes:
      - ./config/b-hunters.ini:/etc/b-hunters/b-hunters.ini
